[package]
name = "s5_store_local"
version = "1.0.0-beta.1"
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
s5_core.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
walkdir = "2.5.0"
