[package]
name = "s5_store_memory"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
bytes.workspace = true
dashmap = "6.1.0"
futures.workspace = true
s5_core.workspace = true
